apiVersion: apps/v1
kind: Deployment
metadata:
  name: mon-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mon-app
  template:
    metadata:
      labels:
        app: mon-app
    spec:
      containers:
        - name: mon-app
          image: oussamaouaddi/mon-app:1.0
          ports:
            - containerPort: 8080

          volumeMounts:
            - name: app-storage
              mountPath: /app/data   # le répertoire où ton app peut écrire
      volumes:
            - name: app-storage
              persistentVolumeClaim:
                claimName: app-pvc
